# Generated by Django 3.0.6 on 2020-06-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(max_length=256, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'SMS',
            },
        ),
    ]
