# Generated by Django 3.0.6 on 2020-05-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First-name', max_length=32, verbose_name='first-name')),
                ('last_name', models.CharField(help_text='Last-name', max_length=32, verbose_name='last-name')),
                ('username', models.CharField(help_text='Username', max_length=32, verbose_name='username')),
                ('phone', models.CharField(help_text='Phone', max_length=16, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
